name: Continuous Integration

on:
    pull_request:
        branches: [ main ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout    
      uses: actions/checkout@v4
      with:
        show-progress: false
            
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies    
      run: dotnet restore src/**

    - name: Build
      run: dotnet build --no-restore src/**

    - name: Test
      run: dotnet test tests/*

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          TestResults/**/*.trx